---
title: "Resume"
---

# Education 

`August 2024:` [Doctor of Philosophy in Public Health]{.underline} - Epidemiology at Florida International University

`August 2021:` [Master of Public Health]{.underline} - Epidemiology at Florida International University

`April 2019:` [Graduate Certificate Program in Molecular and Biomedical Sciences]{.underline} at Florida International University

`April 2018:` [Bachelor of Science in Biology]{.underline} at Florida International University

`April 2018:` [Bachelor of Arts in Psychology and Interdisciplinary Studies]{.underline} at Florida International University

# Fellowship Training 

`August 2022 - Current:` [NIDA T-32 Predoctoral Fellow]{.underline} in association with Florida International University

-   Throughout this fellowship, I have been attending weekly seminars held by experts in three subfields that will further expand my knowledge on Substance Use Disorders, their theoretical framework as well as treatments in clinical settings.   

# Peer-Reviewed Manuscripts, Abstracts, and Posters

Ertanir, B., Cobb, C. L., Unger, J. B., Celada-Dalton, T., West, A. E., Zeledon, I., Perazzo, P. A., Cano, M. Á., Des Rosiers, S. E., Duque, M. C., Ozer, S., Cruz, N., Scaramutti, C., Vos, S. R., Salas-Wright, C. P., Maldonado-Molina, M. M., **Nehme, L**., Martinez, C. R., Zayas, L. H., &amp; Schwartz, S. J. (2023). Crisis migration adverse childhood events: A new category of Youth Adversity for Crisis Migrant Children and Adolescents. *Research on Child and Adolescent Psychopathology*. https://doi.org/10.1007/s10802-022-01016-x

Rahman, A., Sánchez, M., Bursac, Z., Whiting, C. Y., Piña-Watson, B., Taskin, T., Ramírez-Ortiz, D., Leinaar, E., Estrada, Y., Lozano, A. D., **Nehme, L.**, & Cano, M. A. Depressive symptoms among Hispanic emerging adults: Examining the roles of family cohesion and acculturation gap conflicts. *Family Relations.*

Taskin T., Torres L., Roncancio A. M.,Valente M. J., Fernandez A., Rahman A., **Nehme L.**, Okeke D., Lozano A. D., Ruiz E. & Cano M. A. (under review). Acculturative Stress and Self-rated Health among Hispanic Emerging Adults: Examining the Moderating Effects of Social Environment and Social Support. *Journal of Immigrant and Minority Health.*

Cano, M. A., Rahman, R., **Nehme, L**., Okeke, D., & Meek, R. (2022, September). *Ethnic discrimination and psychosocial stress among Hispanic emerging adults: Examining the role of distress tolerance and optimism as coping resources*. Poster presented at the conference of the National Hispanic Science Network on Drug Abuse, Grand Rapids, MI.

# Work Experience 

`August 2021 - August 2022:` [Graduate Assistant]{.underline}

As a graduate assistant, I work alongside two professors, Dr. Cano, and Dr. Pekovic in ensuring a smooth classroom experience. 

I am responsible for responding to students and grading assignments in the following courses

-   PHC 6003 (Chronic Disease Epidemiology) 

-   PHC 6000 (Intro to Epidemiology)

-   PHC 6510 (Advanced Infectious and Tropical Disease Epidemiology) 

-   PHC 6536 (Health Demography) 

`December 2020 - August 2021:` [COVID-19 Contact Tracer, Trainer, Lyme Disease and Enteric Disease Investigator]{.underline}

-   Since communicable diseases are easily spread, as a contact tracer and trainer I was to identify, trace back and contact exposed and infected individuals to whom I provided CDC guidelines on proper quarantine and isolation measures. I additionally helped train incoming contact tracers by educating them on the science of the disease and how to contact trace accordingly.

-   As vaccine efforts have rolled out, I have had the pleasure in helping people achieve their civic duty by scheduling them for their vaccination appointments.  

-   I investigate potential Lyme disease cases and Enteric diseases for the county by reviewing medical records and patient history in order to report appropriately the incidence rates for the county.

`October 2020 - August 2021:` [COVID-19 Town Hall]{.underline}

-   I was working alongside experts to address questions about COVID-19 vaccines, testing and guidelines.

-   Data-Collecting, education and building confidence while growing the trust with 700 members of the community.

`September 2019 - March 2020:` [Interim School Counselor]{.underline}

-   Counseled students throughout major life decisions (classes to take, eligibility, colleges to decide on, what to expect, etc.), along with having written countless of their recommendation letters

-   Advised students with mental health issues along with numerous crises they might be facing and supported students who needed additional help academically 

-   Tutored and substituted for teachers and taught Psychology, Biology and French IB courses

-   Helped create the master board for the upcoming school year

`December 2017 - May 2018:` [Medical Scribe]{.underline}

-   Documented the Electronic Medical Records of patients on the behalf of the attending physician 

-   Charted medical information based upon a physician-patient interaction

-   Familiarized and become fluent in the medical language 

-   Utilized efficient communication within the professional medical field (physicians, nurses, technicians) 

# Research Experience

`August 2020 - Current:` [Research Assistant]{.underline}

-   Assist with literature searches and reviews for manuscripts.

-   Assist with the writing and development of peer-review manuscripts. 

`August 2016 - December 2018:` [Research Assistant for the Investigative Laboratory]{.underline}

-   Interviewed through rapport (or no rapport) building with 30 participants weekly  

-   Scored for 500+ files for two different experiments   

-   Medical screener for the Alcohol experiment to identify healthy participants

-   Trained 20-30 new research assistants on behalf of the lab

-   On stand-by for bartending and interview roles

`October 2016 - February 2017:` [Miami Med Tech]{.underline}

-   Worked in the Biomedical Engineering field alongside engineers, doctors and lawyers to develop new technology to improve medical equipment and develop new ones. 

`December 2016 - April 2016:` [Research Assistant at the Clinical Science in Child and Adolescent Psychology Laboratory]{.underline}

-   Recruited Post-Partum mothers within the hospital, provided education about the study, and handed out 

# Student Involvement/Leadership Experience

`October 2017 - March 2018:` [Alternative Breaks Mission Trip]{.underline}

-   Fundraised money with my mission trip group including canning, bake sales, car washes, etc.

-   Volunteered at Park Center of Mental Health in Nashville with adults looking to enter the work field

-   Understood and gained knowledge in the importance of proper communication and treatment with those suffering from mental illnesses

-   Sorted through and organized clothing items at the Park Center Homelessness Shelter\'s warehouse

-   Partnered with Project Cure for 3 days and helped package about \$2 million worth of medical supplies that were shipped to Ghana, Nigeria and Côte d\'Ivoire

`August 2016 - Current:` [Phi Delta Epsilon Medical Fraternity Member and Dance Marathon Captain]{.underline}

-   Active member and participant in chapter activities and volunteer work for our associated philanthropy; Children\'s Miracle Network

-   Recruited a team and helped each of them raise their total monetary goal to participate in the school-wide event

-   Organized multiple fundraising and bake sale events and raised \$2,525 out of the \$100,405.97, for our local Children\'s Miracle Network

-   Managed and preserved the database and attendance of roughly 20 volunteers

-   Adopted a miracle child and gifted her with a banner and basket

`January 2017 - May 2017:` [Peer Led Team Learning (PLTL) Leader]{.underline}

-   Organized a weekly review session for Biology II students

-   Guided a group of students through a review of course materials 

`August 2015 - December 2015:` [Peer Mentor]{.underline}

-   Assisted an assigned professor during the entire semester of a First Year Experience course

-   Guided students through their collegiate experience and informed them about the advantages of attending Florida International University

-   Introduced students to different departments and the numerous organizations offered on and off campus 

`August 2014 - December 2014:` [Alpha Chi Omega Founding VP Facility of Operations]{.underline}

-   Collaborated with the established executive board to ensure a smooth development of this newly founded fraternity

-   Planned and reserved venues for meetings, events, and socials regarding our philanthropy against domestic violence 

# Skills

[Language:]{.underline}

-   Trilingual in Arabic, English, and French

[Technical:]{.underline}

-   Knowledge, experience, and understanding of R (Base and Tidyverse), Git, R markdown, SAS, and SPSS.

-   Proficient in Microsoft Office Suite, iMovie and Editing skills.

# Awards/Certificates

`January 2022:` Omicron Delta Kappa- National Leadership Honor Society   

`March 2018:` Psi Chi International Honor Society Membership

`March 2015:` Society of Epidemiology Research, Member
